fixtures:
  repositories:
    puppi: 'git://github.com/example42/puppi.git'
    apt: 'git://github.com/example42/puppet-apt.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    salt: "#{source_dir}"
