script: ./script/cibuild
bundler_args: --without development debug
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=2.7.23
  - PUPPET_VERSION=3.3.2
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.23
